//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromedaDataAccessEntityFramework.Model.AndroAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyAndromedaRole
    {
        public MyAndromedaRole()
        {
            this.MyAndromedaPermissions = new HashSet<MyAndromedaPermission>();
            this.MyAndromedaUsers = new HashSet<MyAndromedaUser>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<MyAndromedaPermission> MyAndromedaPermissions { get; set; }
        public virtual ICollection<MyAndromedaUser> MyAndromedaUsers { get; set; }
    }
}
