//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromedaDataAccessEntityFramework.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AndroAdminEntities : DbContext
    {
        public AndroAdminEntities()
            : base("name=AndroAdminEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Address> Addresses { get; set; }
        public DbSet<AMSServer> AMSServers { get; set; }
        public DbSet<Day> Days { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<FTPSite> FTPSites { get; set; }
        public DbSet<FTPSiteType> FTPSiteTypes { get; set; }
        public DbSet<Group> Groups { get; set; }
        public DbSet<Log> Logs { get; set; }
        public DbSet<MyAndromedaUser> MyAndromedaUsers { get; set; }
        public DbSet<MyAndromedaUserGroup> MyAndromedaUserGroups { get; set; }
        public DbSet<MyAndromedaUserStore> MyAndromedaUserStores { get; set; }
        public DbSet<OpeningHour> OpeningHours { get; set; }
        public DbSet<Partner> Partners { get; set; }
        public DbSet<Store> Stores { get; set; }
        public DbSet<StoreAMSServer> StoreAMSServers { get; set; }
        public DbSet<StoreAMSServerFtpSite> StoreAMSServerFtpSites { get; set; }
        public DbSet<StoreAMSServerFTPSitePair> StoreAMSServerFTPSitePairs { get; set; }
        public DbSet<StoreGroup> StoreGroups { get; set; }
        public DbSet<StoreStatu> StoreStatus { get; set; }
    }
}
