//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromedaDataAccessEntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreAMSServerFTPSitePair
    {
        public int Id { get; set; }
        public int StoreId { get; set; }
        public int Priority { get; set; }
        public int AMSServerId { get; set; }
        public Nullable<int> PrimaryFTPSiteId { get; set; }
        public Nullable<int> SecondaryFTPSiteId { get; set; }
    
        public virtual AMSServer AMSServer { get; set; }
        public virtual FTPSite FTPSite { get; set; }
        public virtual FTPSite FTPSite1 { get; set; }
        public virtual Store Store { get; set; }
    }
}
