//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroAdminDataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AndroWebOrderingTheme
    {
        public int Id { get; set; }
        public string Source { get; set; }
        public int Height { get; set; }
        public int Width { get; set; }
        public string FileName { get; set; }
        public string InternalName { get; set; }
        public string Description { get; set; }
    }
}
