//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroAdminDataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chains_Parent_Child
    {
        public int ChainId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ParentChainId { get; set; }
    }
}
