//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroAdminDataAccess.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.MyAndromedaUserGroups = new HashSet<MyAndromedaUserGroup>();
            this.StoreGroups = new HashSet<StoreGroup>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PartnerId { get; set; }
        public string GroupName { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string ExternalId { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual ICollection<MyAndromedaUserGroup> MyAndromedaUserGroups { get; set; }
        public virtual ICollection<StoreGroup> StoreGroups { get; set; }
    }
}
