//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("AndroUsersModel", "FK_tbl_AndroUserPermission_tbl_AndroUser", "tbl_AndroUser", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AndroUsersDataAccess.EntityFramework.tbl_AndroUser), "tbl_AndroUserPermission", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AndroUsersDataAccess.EntityFramework.tbl_AndroUserPermission), true)]
[assembly: EdmRelationshipAttribute("AndroUsersModel", "FK_tbl_AndroUserPermission_tbl_Project", "tbl_Project", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AndroUsersDataAccess.EntityFramework.tbl_Project), "tbl_AndroUserPermission", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AndroUsersDataAccess.EntityFramework.tbl_AndroUserPermission), true)]

#endregion

namespace AndroUsersDataAccess.EntityFramework
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AndroUsersEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AndroUsersEntities1 object using the connection string found in the 'AndroUsersEntities1' section of the application configuration file.
        /// </summary>
        public AndroUsersEntities1() : base("name=AndroUsersEntities1", "AndroUsersEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AndroUsersEntities1 object.
        /// </summary>
        public AndroUsersEntities1(string connectionString) : base(connectionString, "AndroUsersEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AndroUsersEntities1 object.
        /// </summary>
        public AndroUsersEntities1(EntityConnection connection) : base(connection, "AndroUsersEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_AndroUser> tbl_AndroUser
        {
            get
            {
                if ((_tbl_AndroUser == null))
                {
                    _tbl_AndroUser = base.CreateObjectSet<tbl_AndroUser>("tbl_AndroUser");
                }
                return _tbl_AndroUser;
            }
        }
        private ObjectSet<tbl_AndroUser> _tbl_AndroUser;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_AndroUserPermission> tbl_AndroUserPermission
        {
            get
            {
                if ((_tbl_AndroUserPermission == null))
                {
                    _tbl_AndroUserPermission = base.CreateObjectSet<tbl_AndroUserPermission>("tbl_AndroUserPermission");
                }
                return _tbl_AndroUserPermission;
            }
        }
        private ObjectSet<tbl_AndroUserPermission> _tbl_AndroUserPermission;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbl_Project> tbl_Project
        {
            get
            {
                if ((_tbl_Project == null))
                {
                    _tbl_Project = base.CreateObjectSet<tbl_Project>("tbl_Project");
                }
                return _tbl_Project;
            }
        }
        private ObjectSet<tbl_Project> _tbl_Project;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_AndroUser EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_AndroUser(tbl_AndroUser tbl_AndroUser)
        {
            base.AddObject("tbl_AndroUser", tbl_AndroUser);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_AndroUserPermission EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_AndroUserPermission(tbl_AndroUserPermission tbl_AndroUserPermission)
        {
            base.AddObject("tbl_AndroUserPermission", tbl_AndroUserPermission);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbl_Project EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbl_Project(tbl_Project tbl_Project)
        {
            base.AddObject("tbl_Project", tbl_Project);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AndroUsersModel", Name="tbl_AndroUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_AndroUser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_AndroUser object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="surName">Initial value of the SurName property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        /// <param name="emailAddress">Initial value of the EmailAddress property.</param>
        /// <param name="active">Initial value of the Active property.</param>
        /// <param name="created">Initial value of the Created property.</param>
        public static tbl_AndroUser Createtbl_AndroUser(global::System.Int32 id, global::System.String firstName, global::System.String surName, global::System.String password, global::System.String emailAddress, global::System.Boolean active, global::System.DateTime created)
        {
            tbl_AndroUser tbl_AndroUser = new tbl_AndroUser();
            tbl_AndroUser.id = id;
            tbl_AndroUser.FirstName = firstName;
            tbl_AndroUser.SurName = surName;
            tbl_AndroUser.Password = password;
            tbl_AndroUser.EmailAddress = emailAddress;
            tbl_AndroUser.Active = active;
            tbl_AndroUser.Created = created;
            return tbl_AndroUser;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SurName
        {
            get
            {
                return _SurName;
            }
            set
            {
                OnSurNameChanging(value);
                ReportPropertyChanging("SurName");
                _SurName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("SurName");
                OnSurNameChanged();
            }
        }
        private global::System.String _SurName;
        partial void OnSurNameChanging(global::System.String value);
        partial void OnSurNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Active
        {
            get
            {
                return _Active;
            }
            set
            {
                OnActiveChanging(value);
                ReportPropertyChanging("Active");
                _Active = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Active");
                OnActiveChanged();
            }
        }
        private global::System.Boolean _Active;
        partial void OnActiveChanging(global::System.Boolean value);
        partial void OnActiveChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Created
        {
            get
            {
                return _Created;
            }
            set
            {
                OnCreatedChanging(value);
                ReportPropertyChanging("Created");
                _Created = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Created");
                OnCreatedChanged();
            }
        }
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AndroUsersModel", "FK_tbl_AndroUserPermission_tbl_AndroUser", "tbl_AndroUserPermission")]
        public EntityCollection<tbl_AndroUserPermission> tbl_AndroUserPermission
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_AndroUserPermission>("AndroUsersModel.FK_tbl_AndroUserPermission_tbl_AndroUser", "tbl_AndroUserPermission");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_AndroUserPermission>("AndroUsersModel.FK_tbl_AndroUserPermission_tbl_AndroUser", "tbl_AndroUserPermission", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AndroUsersModel", Name="tbl_AndroUserPermission")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_AndroUserPermission : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_AndroUserPermission object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="androUser">Initial value of the AndroUser property.</param>
        /// <param name="project">Initial value of the Project property.</param>
        public static tbl_AndroUserPermission Createtbl_AndroUserPermission(global::System.Int32 id, global::System.Int32 androUser, global::System.Int32 project)
        {
            tbl_AndroUserPermission tbl_AndroUserPermission = new tbl_AndroUserPermission();
            tbl_AndroUserPermission.id = id;
            tbl_AndroUserPermission.AndroUser = androUser;
            tbl_AndroUserPermission.Project = project;
            return tbl_AndroUserPermission;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AndroUser
        {
            get
            {
                return _AndroUser;
            }
            set
            {
                OnAndroUserChanging(value);
                ReportPropertyChanging("AndroUser");
                _AndroUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AndroUser");
                OnAndroUserChanged();
            }
        }
        private global::System.Int32 _AndroUser;
        partial void OnAndroUserChanging(global::System.Int32 value);
        partial void OnAndroUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Project
        {
            get
            {
                return _Project;
            }
            set
            {
                OnProjectChanging(value);
                ReportPropertyChanging("Project");
                _Project = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Project");
                OnProjectChanged();
            }
        }
        private global::System.Int32 _Project;
        partial void OnProjectChanging(global::System.Int32 value);
        partial void OnProjectChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AndroUsersModel", "FK_tbl_AndroUserPermission_tbl_AndroUser", "tbl_AndroUser")]
        public tbl_AndroUser tbl_AndroUser
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_AndroUser>("AndroUsersModel.FK_tbl_AndroUserPermission_tbl_AndroUser", "tbl_AndroUser").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_AndroUser>("AndroUsersModel.FK_tbl_AndroUserPermission_tbl_AndroUser", "tbl_AndroUser").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_AndroUser> tbl_AndroUserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_AndroUser>("AndroUsersModel.FK_tbl_AndroUserPermission_tbl_AndroUser", "tbl_AndroUser");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_AndroUser>("AndroUsersModel.FK_tbl_AndroUserPermission_tbl_AndroUser", "tbl_AndroUser", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AndroUsersModel", "FK_tbl_AndroUserPermission_tbl_Project", "tbl_Project")]
        public tbl_Project tbl_Project
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Project>("AndroUsersModel.FK_tbl_AndroUserPermission_tbl_Project", "tbl_Project").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Project>("AndroUsersModel.FK_tbl_AndroUserPermission_tbl_Project", "tbl_Project").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tbl_Project> tbl_ProjectReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tbl_Project>("AndroUsersModel.FK_tbl_AndroUserPermission_tbl_Project", "tbl_Project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tbl_Project>("AndroUsersModel.FK_tbl_AndroUserPermission_tbl_Project", "tbl_Project", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="AndroUsersModel", Name="tbl_Project")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbl_Project : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbl_Project object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="url">Initial value of the Url property.</param>
        public static tbl_Project Createtbl_Project(global::System.Int32 id, global::System.String name, global::System.String url)
        {
            tbl_Project tbl_Project = new tbl_Project();
            tbl_Project.id = id;
            tbl_Project.Name = name;
            tbl_Project.Url = url;
            return tbl_Project;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("AndroUsersModel", "FK_tbl_AndroUserPermission_tbl_Project", "tbl_AndroUserPermission")]
        public EntityCollection<tbl_AndroUserPermission> tbl_AndroUserPermission
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tbl_AndroUserPermission>("AndroUsersModel.FK_tbl_AndroUserPermission_tbl_Project", "tbl_AndroUserPermission");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tbl_AndroUserPermission>("AndroUsersModel.FK_tbl_AndroUserPermission_tbl_Project", "tbl_AndroUserPermission", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
