//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromedaDataAccessEntityFramework.Model.MyAndromeda
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public MenuItem()
        {
            this.MenuItemGroups = new HashSet<MenuItemGroup>();
            this.SiteMenus = new HashSet<SiteMenu>();
        }
    
        public System.Guid Id { get; set; }
        public int ItemId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<MenuItemGroup> MenuItemGroups { get; set; }
        public virtual ICollection<SiteMenu> SiteMenus { get; set; }
    }
}
