//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAndromedaDataAccessEntityFramework.Model.MyAndromeda
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteMenuPublishTask
    {
        public int Id { get; set; }
        public System.Guid SiteMenuId { get; set; }
        public System.DateTime PublishOnUtc { get; set; }
        public bool Completed { get; set; }
        public bool Canceled { get; set; }
        public string PublishedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual SiteMenu SiteMenu { get; set; }
    }
}
