//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroCloudDataAccessEntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HubHost
    {
        public HubHost()
        {
            this.Sites = new HashSet<Site>();
        }
    
        public System.Guid Id { get; set; }
        public string Url { get; set; }
    
        public virtual ICollection<Site> Sites { get; set; }
    }
}
