//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroCloudDataAccessEntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders_vw
    {
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public int AndroID { get; set; }
        public string ExternalSiteName { get; set; }
        public Nullable<int> RamesesOrderNum { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string datatype { get; set; }
        public string Packet { get; set; }
        public string PartnerOrderID { get; set; }
        public string SiteExternalID { get; set; }
        public string Result { get; set; }
    }
}
