//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroCloudDataAccessEntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorePaymentProvider
    {
        public StorePaymentProvider()
        {
            this.Sites = new HashSet<Site>();
        }
    
        public int ID { get; set; }
        public string ProviderName { get; set; }
        public string ClientId { get; set; }
        public string ClientPassword { get; set; }
    
        public virtual ICollection<Site> Sites { get; set; }
    }
}
