//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataWarehouseDataAccessEntityFramework.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLoyalty
    {
        public System.Guid Id { get; set; }
        public System.Guid OrderId { get; set; }
        public Nullable<decimal> PointsGained { get; set; }
        public Nullable<decimal> PointsUsed { get; set; }
        public Nullable<decimal> PointsMoneyValueGained { get; set; }
        public Nullable<decimal> PointsMoneyValueSpent { get; set; }
        public string ProviderName { get; set; }
    
        public virtual OrderHeader OrderHeader { get; set; }
    }
}
